### PR TITLE
.NET Core Test Suite & GetOccurrences StackOverflow Fix

### PR DESCRIPTION
**Pull request by thoemy**
Overflow happens because this[0] calls this.Skip(0).FirstOrDefault()
which calls this[0] again.

### CODE REVIEW

**Comment by rianjs** [comment]
* Does this bug only exist in the .NET Core version, or does it exist in v2 as well? If it's also present in v2, can you make the change there as well?
* ~~Is there an issue # to go with it? If so, can you add it to the commit message?~~
* Is there a test case that we can add to the unit tests to ensure no future regressions?

Edit: I see, it's issue #252. It sounded familiar. Should probably add the sample code to the unit tests for both .NET Core and v2...

**Comment by thoemy** [comment]
The issue fixed by this is #257 and the problem does not affect v2. The current .Net Core test suit throws a StackOverflow exception without these changes. It's hard to tell if the fix is correct because there seems to be fundamental problem with `GroupedList`.

I'll check if I manage to fix the `GroupedList` problem. But seeing many lines of commented code I assume it is not done yet.

**Comment by thoemy** [comment]
I have managed to get the Test Suite to work and I had to replace the .Net Core Collections classes with the most recent ones from v2, to make the tests pass (4 are skipped).

Without the fix for #257 the test suite will not work.

Please review.

**Comment by pritesha** [comment]
Hi , I ran into similar issue today . can you please help me to get the fix .

**Comment by thoemy** [comment]
Hi @pritesha,
there is no prebuilt package but  this https://github.com/thoemy/ical.net/tree/patch-1 is the branch the Pull Request is based on. Clone/Download it and build it yourself or add the projects as a reference.

**Comment by pritesha** [comment]
Hi @thoemy ,
Thanks for the quick reply.
I atually tried to build the solution locally , however i am using visual studio 2015 , and i cant open the solution in it , I had below errors 

```
C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\Ical.Net\Ical.Net.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\Ical.Net\Ical.Net.csproj

C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\Ical.Net.Collections\Ical.Net.Collections.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\Ical.Net.Collections\Ical.Net.Collections.csproj

C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\antlr.runtime\antlr.runtime.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\antlr.runtime\antlr.runtime.csproj

C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\Ical.Net.UnitTests\Ical.Net.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\ical.Net\ical.net-patch-1\net-core\Ical.Net\Ical.Net.UnitTests\Ical.Net.UnitTests.csproj
```

Is there any way you can give me a intermediate build ,

**Comment by thoemy** [comment]
I currently cannot provide you with a build. Try the VS 2017 Community edition or the Build Tools for Visual Studio 2017 from https://www.visualstudio.com/de/downloads/.

**Comment by pritesha** [comment]
Hi @thoemy ,

I did the build with community edition 2017 , and tried to add the reference into VS  2015. 
However VS 2015 doesn't  allow adding loose dll as a references , it has to be a nugget package.
2017-06-02 10_49_54-microsoft edge
The only purpose I was using ical.net was to parse the created recurrence rule and generate the occurrences ,  I have a deadline , I may have to change the approach now as I cant proceed with using ical.net :( . If you can tell me probable date by when this can be released , I might have to decide the future approach.

**Comment by rianjs** [comment]
This is a substantial body of work, thanks @thoemy!

**Review by rianjs — APPROVED** [review]

**Comment by rianjs** [comment]
Published in Ical.Net 3.0.9-net-core-beta:
https://www.nuget.org/packages/Ical.Net/

**Pull request merged**
