### PR TITLE
VTimeZone DAYLIGHT and STANDARD collections

### PR DESCRIPTION
**Pull request by beriniwlew**
VTimeZone.FromSystemTimeZone method now generates DAYLIGHT or STANDARD collections

### CODE REVIEW

**Comment by beriniwlew** [comment]
New to github.  I didn't realize this pull request would include ALL my commits.

**Comment by mattwoberts** [comment]
Hi. This looks interesting - it adds support for adding the `vtimezone` data to the ical feed, is that correct? Is there a reason it's not been reviewed or accepted?

**Comment by beriniwlew** [comment]
Correct.

I didn't follow some of the guidelines of making a proper pull request...  so I'm assuming it's that.

**Comment by rianjs** [comment]
I haven’t had the time or energy is all.

**Comment by beriniwlew** [comment]
Ok, whew!  At least I'm not being ignored. ;)

**Comment by railapex** [comment]
Any news on this one, or anything I can do to help out? This is a blocker for us being able to upgrade from DDay.iCal...

**Comment by rianjs** [comment]
I’ll have a look at it in the next few days. I have some major breaking changes I’m making right now. (I.e., v4 is on the way.)

**Comment by rianjs** [comment]
I love this change. I'm sorry I didn't get to it sooner. It's implemented exactly how I would have done it (using the NodaTime databases), and even the design and coding style is similar.

I'm not going to merge this PR. I'm going to lift its changes into the version in `net-core`, whose major version will be bumped to `4` this week. v4 contains many more bugfixes ( #320, #330, #331, #332, #318 ), and thematically is almost entirely time-focused, so this fits with that theme very nicely.

At this point, I have to stop supporting v2.

**Comment by pomoika** [comment]
Is it possible to merge this pull request into v2 as well? Lots of people would be happy to have this functionality in current version of Ical.Net for existing projects that can't use net-core.
Thanks you in advance.

**Comment by rianjs** [comment]
`net-core` targets NetStandard 1.3, which means applications .NET 4.6+ can use it.

Your applications are < 4.6?

**Comment by beriniwlew** [comment]
Awesome! Glad you like it.  I look forward to contributing more! -Cheers

**Comment by rianjs** [comment]
I lifted these changes into `net-core`, which works with NetStandard 1.3+ (which is .NET 4.6+). They're available in nuget version 4.0.0: https://www.nuget.org/packages/Ical.Net/4.0.0

**Comment by pomoika** [comment]
>@rianjs Your applications are < 4.6?

Yes, we have a legacy application that targets .NET 4.0. I would appreciate if you could incorporate this change as is into the final version of Ical.Net v2 nuget package even without future support.
Thanks!

**Comment by rianjs** [comment]
I suppose. v2 really is deprecated, though.

**Comment by rianjs** [comment]
OK, it's 2.3.5 on nuget.

**Comment by jocull** [comment]
Just wanted to chime in and say thank you to everyone who worked on this. We were injecting tzdb timezone identifiers into our iCal feeds which was fine on everything we tested (Google Calendar, iCalendar) with but Outlook, which seems to serialize out using Windows system TZ names. I pull in this change and had us fixed up with real TZ info in no time.

We did try using the `2.3.5` for minimal friction, but it seems to have a hard dependency on NodaTime `1.x` (and we are using `2.x`). I got errors when trying it related to how they rearranged the SystemClock API in `2.x`. The jump from .NET `4.5` to `4.6+` was an easy one though in our case.

**Comment by rianjs** [comment]
> We did try using the 2.3.5 for minimal friction, but it seems to have a hard dependency on NodaTime 1.x (and we are using 2.x). I got errors when trying it related to how they rearranged the SystemClock API in 2.x. The jump from .NET 4.5 to 4.6+ was an easy one though in our case.

There are a few differences between NodaTime v1 and v2, not the least of which are different data sources behind the scenes. I actually had to tweak the unit test assertions for the `net-core` version because they were slightly different for some relatively obscure corner cases/time zones.

**Pull request merged**
