### PR TITLE
Fix when no "SENT-BY" defined, get SentBy will throw exception

### PR DESCRIPTION
**Pull request by idiotsky**

### CODE REVIEW

**Comment by axunonb** [comment]
Thanks for submitting the PR.
Actually there several things to consider while heading to a new v5.
Please understand the comments under this aspect.

The `Organizer` class might require more similar refactoring as proposed in the PR.
Examples:

- The class should up updated to use NRT.
- Should the setter for `SentBy` remove an existing `Parameters` entry?
- The getter for `DirectoryEntry` causes a similar issue. it should return `null` if no `DIR` entry exists.
- Decision about errors when creating the `Uri` - throw or use `null` instead? This may also concern the `ParameterCollectionProxy.Set` method.
- Unit tests missing

@minichma What do you think. Should we fix this issue in an isolated or a "fix it all" context?

**Comment by minichma** [comment]
I agree. This PR certainly is beneficial, but the same improvement as for `SentBy` should also be applied to `DirectoryEntry` at least.

@idiotsky Would you be ready to adjust the PR accordingly?

Generally speaking, I think that representing these values as `Uri` is not the best thing to do, so at some point we might consider replacing all the `Uri` values by simple `string` ones.

**Comment by idiotsky** [comment]
> I agree. This PR certainly is beneficial, but the same improvement as for `SentBy` should also be applied to `DirectoryEntry` at least.
> 
> @idiotsky Would you be ready to adjust the PR accordingly?
> 
> Generally speaking, I think that representing these values as `Uri` is not the best thing to do, so at some point we might consider replacing all the `Uri` values by simple `string` ones.

I agree with replace the Uri to string is better idea.

**Comment by idiotsky** [comment]
I submit the changes, any feed back, I'll try to fix it.

**Review by minichma — APPROVED** [review]
LGTM

**Comment by minichma** [comment]
@idiotsky Thank you!

**Comment by idiotsky** [comment]
> @idiotsky Thank you!

you are welcome

**Comment by Sansoeko** [comment]
Closes #587

**Pull request merged**
