### PR TITLE
Initial AppVeyor configuration

### PR DESCRIPTION
**Pull request by ie-zero**
Basic configuration of AppVeyor which restores NuGet packages, build the Visual Studio projects and executes the Unit Tests.

### CODE REVIEW

**Comment by ie-zero** [comment]
This configuration will not configured to generate the NuGet packages from the source on a successful build.

**Comment by rianjs** [comment]
I have set up continuous delivery pipelines before, but I'm not familiar with AppVeyor, and how it works with GitHub.

Ideally, I want these rules:

1. Pull request is opened
2. A build succeeds or fails. If it fails, it notifies the person who opened it.
3. Changes are made to the pull request, and built after each push
4. Merge to `master`
5. Merge kicks off a different build whose final step is to publish 1-n nuget packages.

Nice to have:

* Release notes validation; those should always be updated.

**Comment by ie-zero** [comment]
I will not claim to be an expert but as I understand it is that once an AppVeyor is configured it will build and run the tests on each Push to every branch in a repository (in this case iCal.NET) except of course a branch is requested explicitly to be excluded. 

Usually, on each push to the master (or another branch) will generate and upload the new NuGet packages. 

The AppVeyor file in this PR will to the build and execute the unit tests but it will do nothing yet with NuGet packages. 

I am certain it is possible to link GitHub PRs to report the status of the build/unit tests from AppVeyor but at the moment I have no clue how it can be accomplished. 

Setting up a project in AppVeyor is simple. If you wish you have have a look at the instructions from the NLog project [NLog - How to build your fork](https://github.com/NLog/NLog/blob/master/howto-build-your-fork.md).

**Comment by dindak** [comment]
Building OSS projects is free to sign up for here https://ci.appveyor.com/signup/free

Once you allow AppVeyor access to the repo, it will install a _pull_request_ and _push_ webhook in github to build & test whenever either event occurs. This results in success/fail statuses to be displayed in PRs.

**Pull request closed without merging**
