### PR TITLE
StringBuilder in IcalParser.cs

### LINKED ISSUE #12: iCalParser.cs should use StringBuilders instead of concatenation
E.g. iCalParser.number()

### PR DESCRIPTION
**Pull request by dahermansson**
Fix #12

### CODE REVIEW

**Comment by rianjs** [comment]
I like to keep my PRs telling a single story, with each commit as a coherent chapter in that story. PRs with a single small commit are totally fine.

This PR has two stories in it:
- StringBuilder: looks OK, except I'd rather you use `var` to declare it. It reduces file churn when types change.
- Parsing issue: I'd point you to the issue you opened for the parse-related commit, also you didn't reference the issue you opened in the commit message (or PR message)

**Comment by rianjs** [comment]
Your PR prompted me to (finally) write a [guide for pull requests](https://github.com/rianjs/ical.net/wiki/Contributing-a-%28good%29-pull-request), and while I was doing that, I wrote a [guide for bug reports](https://github.com/rianjs/ical.net/wiki/Filing-a-%28good%29-bug-report).

**Comment by dahermansson** [comment]
Fixed the PR after your suggestions. 
I do another one to fix the bug I found. My intention from the beginning was not to include it in this PR, it just accidentally did anyway.

**Comment by rianjs** [comment]
Looks good. Can you squash them all down into a single commit with a message like "Use StringBuilders in IcalParser #124"

Then I'll merge it. After the other bug fix is in, I'll build and publish a new nuget package, and update both issues with the relevant commit SHA and nuget version.

**Comment by rianjs** [comment]
Did you mean to close this?

**Comment by dahermansson** [comment]
No, I think Github did it whene I removed the commits to replace them with a singel commit.

**Comment by dahermansson** [comment]
Finaly, ther it is... Hop it's ok and this one is closeable now.

**Comment by rianjs** [comment]
I made you a collaborator. Go ahead and merge it.

In general, please wait a day or three so I can look at your code when you open a PR. I'll usually make some comments, or just say "looks good". If I need more time to review it, I'll let you know that, too.

**Pull request merged**
