### PR TITLE
feat: add natural language de/serialization as a companion package

### LINKED ISSUE #576: Natural Language de/serialization
A very desirable feature of this library, and which exists in similar libraries in other languages (e.g. [Typescript's Equivalent](https://github.com/jakubroztocil/rrule) is the ability to serialize and deserialize to and from natural language, for example:

`Every day at 10, 12 and 17` should deserialize into `FREQ=DAILY;BYHOUR=10,12,17`

and vice versa.

I think this should be implemented as a separate (and optional) NuGet package.

### PR DESCRIPTION
**Pull request by paviad**
Adds natural language serialization and deserialization of recurrence patterns as a separate library.

Closes #576

### CODE REVIEW

**Comment by paviad** [comment]
I just want to give credit where credit is due, the source code here is a manual porting of the code in the Typescript's library from https://github.com/jakubroztocil/rrule

The ported part is the source in the `nlp` folder at https://github.com/jakubroztocil/rrule/tree/master/src/nlp

**Comment by paviad** [comment]
I do not understand these test failures, how do I resolve them?

**Comment by axunonb** [comment]
When clicking the link [42 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=ical-org_ical.net&pullRequest=577&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true) you'll see the solution. It's about a missing timeout for Regex expressions, which is a risk for DoS attacks.
Please also have a look at this [announcement](https://github.com/ical-org/ical.net/discussions/594).

**Comment by axunonb** [comment]
See package [Ical.Net.NaturalLanguage](https://github.com/paviad/ical.net.naturallanguage)

**Pull request closed without merging**
